package com.kevin.appfoodpie.values;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kevin.appfoodpie.values.DataMore;
import com.kevin.appfoodpie.values.Food;
import com.kevin.appfoodpie.values.Url;

import com.kevin.appfoodpie.values.DataMoreDao;
import com.kevin.appfoodpie.values.FoodDao;
import com.kevin.appfoodpie.values.UrlDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataMoreDaoConfig;
    private final DaoConfig foodDaoConfig;
    private final DaoConfig urlDaoConfig;

    private final DataMoreDao dataMoreDao;
    private final FoodDao foodDao;
    private final UrlDao urlDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataMoreDaoConfig = daoConfigMap.get(DataMoreDao.class).clone();
        dataMoreDaoConfig.initIdentityScope(type);

        foodDaoConfig = daoConfigMap.get(FoodDao.class).clone();
        foodDaoConfig.initIdentityScope(type);

        urlDaoConfig = daoConfigMap.get(UrlDao.class).clone();
        urlDaoConfig.initIdentityScope(type);

        dataMoreDao = new DataMoreDao(dataMoreDaoConfig, this);
        foodDao = new FoodDao(foodDaoConfig, this);
        urlDao = new UrlDao(urlDaoConfig, this);

        registerDao(DataMore.class, dataMoreDao);
        registerDao(Food.class, foodDao);
        registerDao(Url.class, urlDao);
    }
    
    public void clear() {
        dataMoreDaoConfig.clearIdentityScope();
        foodDaoConfig.clearIdentityScope();
        urlDaoConfig.clearIdentityScope();
    }

    public DataMoreDao getDataMoreDao() {
        return dataMoreDao;
    }

    public FoodDao getFoodDao() {
        return foodDao;
    }

    public UrlDao getUrlDao() {
        return urlDao;
    }

}
